# -*- coding: utf-8 -*-
"""cnn_first_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmRmPotYUfEYzMZYnyVa1eYAdQsltN9j
"""

# imports
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import time

# check device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu' )
print(f"Using device:{device}")

"""# self = "This Specific Object"

When you do `self.conv1 = nn.Conv2d(...)`, you're saying:
**"Attach conv1 layer to THIS specific object so it stays with the object after __init__ ends"**

Without self → layer disappears after __init__  
With self → layer stays attached to object forever ✓
"""

# Defining Cnn Architecture
class SimpleMedicalCNN(nn.Module): # our parent class is nn.Module ,SimpleMedicalCNN is the CHILD, CHILD CLASS INHERITS FROM NN.MODULE

  """
  Simple CNN for medical image classification

 
  Input (28×28×1)
  → Conv2d(1, 32, 3) + ReLU
  → MaxPool2d(2)
  → Conv2d(32, 64, 3) + ReLU
  → MaxPool2d(2)
  → Flatten
  → Linear(1024, 128) + ReLU
  → Linear(128, 10)
  Output (10 classes)
  """
  def __init__(self):
    super(SimpleMedicalCNN, self).__init__()  # super calls parent's__init__ in SimpleMedicalCNN which is child class , SELF is this object

    # Convolutional layers
    self.conv1= nn.Conv2d(
        in_channels=1,  #grayscale image
        out_channels=32, # 32 feature maps
        kernel_size= 3,
        padding= 1       # keep size same

    )

    self.conv2= nn.Conv2d(
        in_channels= 32,
        out_channels= 64,
        kernel_size= 3,
        padding = 1
    )

    #Pooling
    self.pool=nn.MaxPool2d(
        kernel_size=2,
        stride=2
    )

    # fully connected layer
    self.fc1= nn.Linear(64*7*7,128) # after 2 pooling 28->14->7
    self.fc2= nn.Linear(128,10)   # 10 classes(0-9)

    # activation function
    self.relu= nn.ReLU()
    self.dropout = nn.Dropout(0.5)

  def forward(self, x):
    #convolution block 1
    x= self.relu(self.conv1(x)) #(N , 32, 28 , 28) N = no of images in one batch ,32 feature feature map
    x= self.pool(x)#(N ,32, 14, 14)

    # convolution block 2
    x= self.relu(self.conv2(x))# (N , 64, 14, 14)
    x= self.pool(x)# (N , 64, 7 , 7)

    # flatten
    x = x.view(x.size(0),-1) #(N,3136)

    # FC LAYERS
    x = self.relu(self.fc1(x))
    x= self.dropout(x)
    x= self.fc2(x)

    return(x)

model= SimpleMedicalCNN().to(device) # .to(device):If GPU exists: Model on GPU memory(Fast) , If no GPU: Model on CPU memory (Slow)
print(" Model created successfully!")

# count parameters
total_params = sum(p.numel()for p in model.parameters())
trainable_params = sum(p.numel()for p in model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params}")
print(f"Trainable parameters: {trainable_params}")

print("Model Architecture:")
print(model)

"""#  WHAT DO THESE TWO LINES DO?

## LINE 1: total_params = sum(p.numel() for p in model.parameters())

### Breaking it down:

```python
model.parameters()

Gets all weight matrices in the model

Example:
conv1.weight: shape (32, 1, 3, 3)
conv1.bias: shape (32,)
conv2.weight: shape (64, 32, 3, 3)
fc1.weight: shape (128, 3136)
... etc

for p in model.parameters(): Loop through each parameter

p = conv1.weight (32, 1, 3, 3) (32*1*3*3=288)
p = conv1.bias (32,)
p = conv2.weight (64, 32, 3, 3)
... and so on

p.numel(): Count total numbers in that parameter
sum(...):Add all counts together
288 + 32 + 18,432 + 401,408 + ... = TOTAL_PARAMS

Result: Total number in model (e.g., 52,138 parameters)


LINE 2: trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

Same as Line 1, BUT with condition: if p.requires_grad

if p.requires_grad: Only count parameters that will be trained

Result: Only trainable parameters count (e.g., 50,000 parameters)

COMPARISON: Total vs Trainable:
TOTAL_PARAMS: 52,138
│
├─ trainable_params: 50,000  (will be updated)
│
└─ frozen_params: 2,138      (won't be updated)
"""

# load dataset

transform= transforms.Compose([
    transforms.ToTensor(),                         # PIL → torch.Tensor, scale to 0-1
    transforms.Normalize((0.1307,),(0.3081,))]     # Normalize using mean and std of mnist dataset
)


# Download datasets
train_dataset= datasets.MNIST(
    root = './data',
    train =True ,
    transform= transform,
    download = True
)
test_dataset= datasets.MNIST(
    root='./data',
    train= False,
    transform = transform,
    download = True


)

# create dataloaders
batch_size = 32
train_loader=DataLoader(
    train_dataset,
    batch_size= batch_size,
    shuffle = True,
    num_workers=2
)

test_loader= DataLoader(
    test_dataset,
    batch_size= batch_size,
    shuffle = False,
    num_workers= 2

)

# Without num_workers (or num_workers=0):
# ├─ Main process loads 1 batch
# ├─ Wait for loading to finish
# ├─ Train on batch
# ├─ Load next batch (SLOW - waiting time)
# └─ Train on batch
# Result: GPU sits idle while waiting for data

# With num_workers=2:
# ├─ Thread 1: Loading batch N+1 (while training)
# ├─ Main process: Training on batch N
# ├─ Thread 2: Loading batch N+2 (while training)
# └─ No waiting! Data always ready
# Result: GPU always has data, no idle time


# WITHOUT num_workers=0:
# Time: [Load batch] [Train] [Load batch] [Train] [Load batch] [Train]
#       Loading time wasted

# WITH num_workers=2:
# Time: [Load batch] [Load batch] [Train] [Load batch] [Train]
#       Loading happens while training

# Formula:
# normalized_image = (image - mean) / std

# Step by step:
# 1. Subtract mean (0.1307) from all pixels
# 2. Divide by standard deviation (0.3081)

# Result:
# ├─ Values centered around 0
# ├─ Values between roughly -1 and 1
# └─ Easier for neural network to learn!

# training setup
criterion = nn.CrossEntropyLoss()
optimizer= optim.Adam(model.parameters(), lr = 0.0001)
scheduler= optim.lr_scheduler.StepLR(optimizer, step_size= 2, gamma= 0.1)  # Scheduler: StepLR (reduce lr by 10% every 2 epochs)"

# training loop
# single epoch training
def train_epoch(model, train_loader, criterion, optimizer, device):

    model.train()
    total_loss = 0.0
    correct = 0 # how many correct predictions
    total = 0 # total predictions

    for batch_idx, (images, labels) in enumerate(train_loader):
        images, labels = images.to(device), labels.to(device)

        # Forward pass
        outputs = model(images)     # output.shape (32, 10 )->(no of images , 10 probabilities each) (digits: 0-9)
        loss = criterion(outputs, labels)

        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Statistics
        total_loss += loss.item()   #loss.item() = (loss_img1 + loss_img2 + ... + loss_img32) / 32  = 2.5  (example number)

        _, predicted = torch.max(outputs.data, 1)    #Underscore = "I don't care about this value", It means: "Store something here but I won't use it"
        total += labels.size(0) # shape of labels (32,)
        correct += (predicted == labels).sum().item()

        if (batch_idx + 1) % 500 == 0:
            print(f"  Batch [{batch_idx+1}/{len(train_loader)}]")

    avg_loss = total_loss / len(train_loader)
    accuracy = 100.0 * correct / total
    return avg_loss, accuracy

def test_model(model, test_loader, criterion, device):

    model.eval()
    total_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)

            total_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    avg_loss = total_loss / len(test_loader)
    accuracy = 100.0 * correct / total
    return avg_loss, accuracy

# Train for epochs
num_epochs = 10
train_losses, train_accuracy = [], []
test_losses, test_accuracy = [], []

start_time = time.time()

for epoch in range(num_epochs):
    print(f"\nEpoch [{epoch+1}/{num_epochs}]")

    train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device)
    test_loss, test_acc = test_model(model, test_loader, criterion, device)

    train_losses.append(train_loss)
    train_accuracy.append(train_acc)
    test_losses.append(test_loss)
    test_accuracy.append(test_acc)

    print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}%")
    print(f"Test Loss:  {test_loss:.4f} | Test Acc:  {test_acc:.2f}%")

    scheduler.step()

elapsed_time = time.time() - start_time
print(f" Training complete! (Time: {elapsed_time:.1f} seconds)")
print(f"Final test accuracy: {test_accuracy[-1]:.2f}%")

"""# One image's output
* output = [0.05, 0.1, 0.02, 0.8, 0.01, 0.02, 0.0, 0.0, 0.0, 0.0]
* Prob for 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

# True label
label = 3  ← It's actually digit 3

* Model said digit 3 with probability 0.8
* But probability should be 1.0 (100% sure) for correct digit!

# CrossEntropyLoss calculates:
* loss_image_1 = -log(0.8)
             = 0.223  ← Some error, but not too bad

# Another image:
* output = [0.9, 0.05, 0.02, 0.01, 0.01, 0.01, 0.0, 0.0, 0.0, 0.0]
* label = 3  ← True label is 3, but model said 0.01!

* loss_image_2 = -log(0.01)
             = 4.605  ← BIG ERROR! Model was very wrong
# **loss_item()** this ONE loss value is already the AVERAGE of 32 images
* loss.item() = (loss_img1 + loss_img2 + ... + loss_img32) / 32
            = 2.5  (example number)

* total_loss = loss.item()for batch_1 + ....... loss.item() for last batch

WHY USE _?

torch.max() Returns TWO Things:

torch.max(outputs.data, 1)

Returns:
1. Maximum values:    [0.3, 0.8, 0.7, ...]  (the actual max numbers)
2. Indices (positions): [3, 0, 2, ...]      (where the max is located)

We Only Need the Indices

We care about: Which class won?
We don't care about: How high was the score?

predicted indices = [3, 0, 2, ...]  ← We use this

max values        = [0.3, 0.8, 0.7]  ← We ignore this
"""

# visualising training results '
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Loss curve
axes[0].plot(train_losses, label='Train Loss', marker='o', linewidth=2)
axes[0].plot(test_losses, label='Test Loss', marker='s', linewidth=2)
axes[0].set_xlabel('Epoch', fontsize=11)
axes[0].set_ylabel('Loss', fontsize=11)
axes[0].set_title('Training vs Test Loss', fontsize=12, fontweight='bold')
axes[0].legend(fontsize=10)
axes[0].grid(True, alpha=0.3)

# Accuracy curve
axes[1].plot(train_accuracy, label='Train Accuracy', marker='o', linewidth=2)
axes[1].plot(test_accuracy, label='Test Accuracy', marker='s', linewidth=2)
axes[1].set_xlabel('Epoch', fontsize=11)
axes[1].set_ylabel('Accuracy (%)', fontsize=11)
axes[1].set_title('Training vs Test Accuracy', fontsize=12, fontweight='bold')
axes[1].legend(fontsize=10)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('training_curves.png', dpi=100, bbox_inches='tight')
print(" Saved: training_curves.png")
plt.show()

from google.colab import files
files.download('training_curves.png')

# visualising learned kernels
kernels = model.conv1.weight.data  # Shape: (32, 1, 3, 3)

fig, axes = plt.subplots(4, 8, figsize=(14, 7))
axes = axes.flatten()

for i in range(32):
    kernel = kernels[i, 0].cpu().numpy()  # Get i-th kernel   # to numpy as matplot need numpy so to convert in numpy we have to convert it from gpu tensor to cpu as NumPy can ONLY work with CPU memory, not GPU memory.
    im = axes[i].imshow(kernel, cmap='gray')  # Display as image
    axes[i].set_title(f'K{i}', fontsize=8)
    axes[i].axis('off')

plt.suptitle('32 Learned Kernels from Conv1 Layer (3×3)', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('learned_kernels.png', dpi=100, bbox_inches='tight')
print("Saved: learned_kernels.png")
plt.show()

from google.colab import files
files.download('learned_kernels.png')

"""#  KERNELS, FILTERS & FEATURE DETECTORS

##  WHAT ARE KERNELS?

In a Convolutional Neural Network (CNN), **Kernels**, **Filters**, and **Feature Detectors** are three names for the exact same thing.

In our specific model, the **Conv1** layer has **32 kernels**:
*   **Size:** Each kernel is 3x3 pixels.
*   **Purpose:** Each kernel learns to "look" for a specific feature.
    *   **Kernel 1:** Might detect vertical edges.
    *   **Kernel 2:** Might detect sharp corners.
    *   **Kernel 3:** Might detect rounded curves.



---

##  EXTRACTING KERNELS

To see what the model has actually learned after training, we use the following logic:

`kernels = model.conv1.weight.data`

### Breakdown of the Code:
*   **model.conv1**: Accesses the first convolutional layer we defined as `nn.Conv2d(1, 32, 3, padding=1)`.
*   **weight**: This is the weight matrix of the layer. These weights **are** the kernels.
*   **data**: This extracts the raw numerical tensor and ignores the gradient computation graph (making it easier to process/plot).

---

##  SHAPE EXPLANATION: (32, 1, 3, 3)

The shape of the `kernels` tensor tells us its architecture:

| Dimension | Value | Meaning |
| :--- | :--- | :--- |
| **Index 0** | **32** | Total number of kernels/filters in this layer. |
| **Index 1** | **1** | Number of input channels (1 for grayscale, 3 for RGB). |
| **Index 2** | **3** | Height of the kernel (3 pixels). |
| **Index 3** | **3** | Width of the kernel (3 pixels). |

---

##  WHAT THIS MEANS

The variable `kernels` is essentially a collection of 32 different 3x3 grids. Each grid contains numbers (weights) that were tuned during training to react to specific patterns.

###  Numerical Example
Here is what two of those 32 kernels might look like internally:

**Kernel 0 (Potential Edge Detector):**
$$
\begin{bmatrix}
-0.2 & 0.1 & -0.3 \\
0.4 & -0.5 & 0.2 \\
-0.1 & 0.3 & -0.4
\end{bmatrix}
$$

**Kernel 1 (Potential Corner Detector):**
$$
\begin{bmatrix}
0.1 & -0.2 & 0.4 \\
-0.3 & 0.5 & -0.1 \\
0.2 & -0.4 & 0.3
\end{bmatrix}
$$

---
*By visualizing these weights, we can "see" through the eyes of the AI to understand what parts of an image it thinks are most important!*
"""

# save model
print("Saving model...")
torch.save(model.state_dict(), 'medical_cnn_model.pth')
print(" Saved: medical_cnn_model.pth")

from google.colab import files
files.download('medical_cnn_model.pth')

"""# MODEL.STATE_DICT() - COMPLETE EXPLANATION

## WHAT IS state_dict()?

`state_dict()` is a **Python dictionary** that contains all the **learned weights and biases** of your neural network.

It's like a "snapshot" of everything the model learned during training.

model.state_dict() contains:

* conv1.weight → 32 × 1 × 3 × 3 = 288 values
* conv1.bias → 32 values
* conv2.weight → 64 × 32 × 3 × 3 = 18,432 values
* conv2.bias → 64 values
* fc1.weight → 128 × 3136 = 401,408 values
* fc1.bias → 128 values
* fc2.weight → 10 × 128 = 1,280 values
* fc2.bias → 10 values
* TOTAL: ~421,642 values (the learned parameters!)

#  SAVING THE MODEL STATE

To save your trained model so it can be loaded later without retraining, we follow this workflow:

### **THE PROCESS**

**model.state_dict()**
*   Extracts a dictionary containing all the learned **weights** and **biases** for every layer.

**↓**

**Dictionary with all weights & biases**
*   Organizes the parameters into key-value pairs (e.g., `conv1.weight` → tensor values).

**↓**

**Converted to binary format**
*   PyTorch serializes the dictionary into a compressed binary format (using Pickle).

**↓**

**Saved to file: 'medical_cnn_model.pth'**
*   Writes the data to your disk with the `.pth` or `.pt` extension.

---

### **THE CODE**
```python
# Save the model
torch.save(model.state_dict(), 'medical_cnn_model.pth')

LOADING THE MODEL LATER:

# Create new model with same architecture
new_model = SimpleMedicalCNN()

# Load the saved weights
new_model.load_state_dict(torch.load('medical_cnn_model.pth'))

# Now new_model has all the learned parameters!
"""
